import '../tdapi.dart';

/// Contains notifications about data changes
abstract class Update extends TdObject {
  const Update();

  static const String CONSTRUCTOR = 'update';

  /// Inherited by:
  /// [UpdateAuthorizationState]
  /// [UpdateNewMessage]
  /// [UpdateMessageSendAcknowledged]
  /// [UpdateMessageSendSucceeded]
  /// [UpdateMessageSendFailed]
  /// [UpdateMessageContent]
  /// [UpdateMessageEdited]
  /// [UpdateMessageIsPinned]
  /// [UpdateMessageInteractionInfo]
  /// [UpdateMessageContentOpened]
  /// [UpdateMessageMentionRead]
  /// [UpdateMessageLiveLocationViewed]
  /// [UpdateNewChat]
  /// [UpdateChatTitle]
  /// [UpdateChatPhoto]
  /// [UpdateChatPermissions]
  /// [UpdateChatLastMessage]
  /// [UpdateChatPosition]
  /// [UpdateChatReadInbox]
  /// [UpdateChatReadOutbox]
  /// [UpdateChatActionBar]
  /// [UpdateChatDraftMessage]
  /// [UpdateChatMessageSender]
  /// [UpdateChatMessageTtl]
  /// [UpdateChatNotificationSettings]
  /// [UpdateChatPendingJoinRequests]
  /// [UpdateChatReplyMarkup]
  /// [UpdateChatTheme]
  /// [UpdateChatUnreadMentionCount]
  /// [UpdateChatVideoChat]
  /// [UpdateChatDefaultDisableNotification]
  /// [UpdateChatHasProtectedContent]
  /// [UpdateChatHasScheduledMessages]
  /// [UpdateChatIsBlocked]
  /// [UpdateChatIsMarkedAsUnread]
  /// [UpdateChatFilters]
  /// [UpdateChatOnlineMemberCount]
  /// [UpdateScopeNotificationSettings]
  /// [UpdateNotification]
  /// [UpdateNotificationGroup]
  /// [UpdateActiveNotifications]
  /// [UpdateHavePendingNotifications]
  /// [UpdateDeleteMessages]
  /// [UpdateChatAction]
  /// [UpdateUserStatus]
  /// [UpdateUser]
  /// [UpdateBasicGroup]
  /// [UpdateSupergroup]
  /// [UpdateSecretChat]
  /// [UpdateUserFullInfo]
  /// [UpdateBasicGroupFullInfo]
  /// [UpdateSupergroupFullInfo]
  /// [UpdateServiceNotification]
  /// [UpdateFile]
  /// [UpdateFileGenerationStart]
  /// [UpdateFileGenerationStop]
  /// [UpdateCall]
  /// [UpdateGroupCall]
  /// [UpdateGroupCallParticipant]
  /// [UpdateNewCallSignalingData]
  /// [UpdateUserPrivacySettingRules]
  /// [UpdateUnreadMessageCount]
  /// [UpdateUnreadChatCount]
  /// [UpdateOption]
  /// [UpdateStickerSet]
  /// [UpdateInstalledStickerSets]
  /// [UpdateTrendingStickerSets]
  /// [UpdateRecentStickers]
  /// [UpdateFavoriteStickers]
  /// [UpdateSavedAnimations]
  /// [UpdateSelectedBackground]
  /// [UpdateChatThemes]
  /// [UpdateLanguagePackStrings]
  /// [UpdateConnectionState]
  /// [UpdateTermsOfService]
  /// [UpdateUsersNearby]
  /// [UpdateDiceEmojis]
  /// [UpdateAnimatedEmojiMessageClicked]
  /// [UpdateAnimationSearchParameters]
  /// [UpdateSuggestedActions]
  /// [UpdateNewInlineQuery]
  /// [UpdateNewChosenInlineResult]
  /// [UpdateNewCallbackQuery]
  /// [UpdateNewInlineCallbackQuery]
  /// [UpdateNewShippingQuery]
  /// [UpdateNewPreCheckoutQuery]
  /// [UpdateNewCustomEvent]
  /// [UpdateNewCustomQuery]
  /// [UpdatePoll]
  /// [UpdatePollAnswer]
  /// [UpdateChatMember]
  /// [UpdateNewChatJoinRequest]
  static Update? fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      return null;
    }

    switch (json["@type"]) {
      case UpdateAuthorizationState.CONSTRUCTOR:
        return UpdateAuthorizationState.fromJson(json);
      case UpdateNewMessage.CONSTRUCTOR:
        return UpdateNewMessage.fromJson(json);
      case UpdateMessageSendAcknowledged.CONSTRUCTOR:
        return UpdateMessageSendAcknowledged.fromJson(json);
      case UpdateMessageSendSucceeded.CONSTRUCTOR:
        return UpdateMessageSendSucceeded.fromJson(json);
      case UpdateMessageSendFailed.CONSTRUCTOR:
        return UpdateMessageSendFailed.fromJson(json);
      case UpdateMessageContent.CONSTRUCTOR:
        return UpdateMessageContent.fromJson(json);
      case UpdateMessageEdited.CONSTRUCTOR:
        return UpdateMessageEdited.fromJson(json);
      case UpdateMessageIsPinned.CONSTRUCTOR:
        return UpdateMessageIsPinned.fromJson(json);
      case UpdateMessageInteractionInfo.CONSTRUCTOR:
        return UpdateMessageInteractionInfo.fromJson(json);
      case UpdateMessageContentOpened.CONSTRUCTOR:
        return UpdateMessageContentOpened.fromJson(json);
      case UpdateMessageMentionRead.CONSTRUCTOR:
        return UpdateMessageMentionRead.fromJson(json);
      case UpdateMessageLiveLocationViewed.CONSTRUCTOR:
        return UpdateMessageLiveLocationViewed.fromJson(json);
      case UpdateNewChat.CONSTRUCTOR:
        return UpdateNewChat.fromJson(json);
      case UpdateChatTitle.CONSTRUCTOR:
        return UpdateChatTitle.fromJson(json);
      case UpdateChatPhoto.CONSTRUCTOR:
        return UpdateChatPhoto.fromJson(json);
      case UpdateChatPermissions.CONSTRUCTOR:
        return UpdateChatPermissions.fromJson(json);
      case UpdateChatLastMessage.CONSTRUCTOR:
        return UpdateChatLastMessage.fromJson(json);
      case UpdateChatPosition.CONSTRUCTOR:
        return UpdateChatPosition.fromJson(json);
      case UpdateChatReadInbox.CONSTRUCTOR:
        return UpdateChatReadInbox.fromJson(json);
      case UpdateChatReadOutbox.CONSTRUCTOR:
        return UpdateChatReadOutbox.fromJson(json);
      case UpdateChatActionBar.CONSTRUCTOR:
        return UpdateChatActionBar.fromJson(json);
      case UpdateChatDraftMessage.CONSTRUCTOR:
        return UpdateChatDraftMessage.fromJson(json);
      case UpdateChatMessageSender.CONSTRUCTOR:
        return UpdateChatMessageSender.fromJson(json);
      case UpdateChatMessageTtl.CONSTRUCTOR:
        return UpdateChatMessageTtl.fromJson(json);
      case UpdateChatNotificationSettings.CONSTRUCTOR:
        return UpdateChatNotificationSettings.fromJson(json);
      case UpdateChatPendingJoinRequests.CONSTRUCTOR:
        return UpdateChatPendingJoinRequests.fromJson(json);
      case UpdateChatReplyMarkup.CONSTRUCTOR:
        return UpdateChatReplyMarkup.fromJson(json);
      case UpdateChatTheme.CONSTRUCTOR:
        return UpdateChatTheme.fromJson(json);
      case UpdateChatUnreadMentionCount.CONSTRUCTOR:
        return UpdateChatUnreadMentionCount.fromJson(json);
      case UpdateChatVideoChat.CONSTRUCTOR:
        return UpdateChatVideoChat.fromJson(json);
      case UpdateChatDefaultDisableNotification.CONSTRUCTOR:
        return UpdateChatDefaultDisableNotification.fromJson(json);
      case UpdateChatHasProtectedContent.CONSTRUCTOR:
        return UpdateChatHasProtectedContent.fromJson(json);
      case UpdateChatHasScheduledMessages.CONSTRUCTOR:
        return UpdateChatHasScheduledMessages.fromJson(json);
      case UpdateChatIsBlocked.CONSTRUCTOR:
        return UpdateChatIsBlocked.fromJson(json);
      case UpdateChatIsMarkedAsUnread.CONSTRUCTOR:
        return UpdateChatIsMarkedAsUnread.fromJson(json);
      case UpdateChatFilters.CONSTRUCTOR:
        return UpdateChatFilters.fromJson(json);
      case UpdateChatOnlineMemberCount.CONSTRUCTOR:
        return UpdateChatOnlineMemberCount.fromJson(json);
      case UpdateScopeNotificationSettings.CONSTRUCTOR:
        return UpdateScopeNotificationSettings.fromJson(json);
      case UpdateNotification.CONSTRUCTOR:
        return UpdateNotification.fromJson(json);
      case UpdateNotificationGroup.CONSTRUCTOR:
        return UpdateNotificationGroup.fromJson(json);
      case UpdateActiveNotifications.CONSTRUCTOR:
        return UpdateActiveNotifications.fromJson(json);
      case UpdateHavePendingNotifications.CONSTRUCTOR:
        return UpdateHavePendingNotifications.fromJson(json);
      case UpdateDeleteMessages.CONSTRUCTOR:
        return UpdateDeleteMessages.fromJson(json);
      case UpdateChatAction.CONSTRUCTOR:
        return UpdateChatAction.fromJson(json);
      case UpdateUserStatus.CONSTRUCTOR:
        return UpdateUserStatus.fromJson(json);
      case UpdateUser.CONSTRUCTOR:
        return UpdateUser.fromJson(json);
      case UpdateBasicGroup.CONSTRUCTOR:
        return UpdateBasicGroup.fromJson(json);
      case UpdateSupergroup.CONSTRUCTOR:
        return UpdateSupergroup.fromJson(json);
      case UpdateSecretChat.CONSTRUCTOR:
        return UpdateSecretChat.fromJson(json);
      case UpdateUserFullInfo.CONSTRUCTOR:
        return UpdateUserFullInfo.fromJson(json);
      case UpdateBasicGroupFullInfo.CONSTRUCTOR:
        return UpdateBasicGroupFullInfo.fromJson(json);
      case UpdateSupergroupFullInfo.CONSTRUCTOR:
        return UpdateSupergroupFullInfo.fromJson(json);
      case UpdateServiceNotification.CONSTRUCTOR:
        return UpdateServiceNotification.fromJson(json);
      case UpdateFile.CONSTRUCTOR:
        return UpdateFile.fromJson(json);
      case UpdateFileGenerationStart.CONSTRUCTOR:
        return UpdateFileGenerationStart.fromJson(json);
      case UpdateFileGenerationStop.CONSTRUCTOR:
        return UpdateFileGenerationStop.fromJson(json);
      case UpdateCall.CONSTRUCTOR:
        return UpdateCall.fromJson(json);
      case UpdateGroupCall.CONSTRUCTOR:
        return UpdateGroupCall.fromJson(json);
      case UpdateGroupCallParticipant.CONSTRUCTOR:
        return UpdateGroupCallParticipant.fromJson(json);
      case UpdateNewCallSignalingData.CONSTRUCTOR:
        return UpdateNewCallSignalingData.fromJson(json);
      case UpdateUserPrivacySettingRules.CONSTRUCTOR:
        return UpdateUserPrivacySettingRules.fromJson(json);
      case UpdateUnreadMessageCount.CONSTRUCTOR:
        return UpdateUnreadMessageCount.fromJson(json);
      case UpdateUnreadChatCount.CONSTRUCTOR:
        return UpdateUnreadChatCount.fromJson(json);
      case UpdateOption.CONSTRUCTOR:
        return UpdateOption.fromJson(json);
      case UpdateStickerSet.CONSTRUCTOR:
        return UpdateStickerSet.fromJson(json);
      case UpdateInstalledStickerSets.CONSTRUCTOR:
        return UpdateInstalledStickerSets.fromJson(json);
      case UpdateTrendingStickerSets.CONSTRUCTOR:
        return UpdateTrendingStickerSets.fromJson(json);
      case UpdateRecentStickers.CONSTRUCTOR:
        return UpdateRecentStickers.fromJson(json);
      case UpdateFavoriteStickers.CONSTRUCTOR:
        return UpdateFavoriteStickers.fromJson(json);
      case UpdateSavedAnimations.CONSTRUCTOR:
        return UpdateSavedAnimations.fromJson(json);
      case UpdateSelectedBackground.CONSTRUCTOR:
        return UpdateSelectedBackground.fromJson(json);
      case UpdateChatThemes.CONSTRUCTOR:
        return UpdateChatThemes.fromJson(json);
      case UpdateLanguagePackStrings.CONSTRUCTOR:
        return UpdateLanguagePackStrings.fromJson(json);
      case UpdateConnectionState.CONSTRUCTOR:
        return UpdateConnectionState.fromJson(json);
      case UpdateTermsOfService.CONSTRUCTOR:
        return UpdateTermsOfService.fromJson(json);
      case UpdateUsersNearby.CONSTRUCTOR:
        return UpdateUsersNearby.fromJson(json);
      case UpdateDiceEmojis.CONSTRUCTOR:
        return UpdateDiceEmojis.fromJson(json);
      case UpdateAnimatedEmojiMessageClicked.CONSTRUCTOR:
        return UpdateAnimatedEmojiMessageClicked.fromJson(json);
      case UpdateAnimationSearchParameters.CONSTRUCTOR:
        return UpdateAnimationSearchParameters.fromJson(json);
      case UpdateSuggestedActions.CONSTRUCTOR:
        return UpdateSuggestedActions.fromJson(json);
      case UpdateNewInlineQuery.CONSTRUCTOR:
        return UpdateNewInlineQuery.fromJson(json);
      case UpdateNewChosenInlineResult.CONSTRUCTOR:
        return UpdateNewChosenInlineResult.fromJson(json);
      case UpdateNewCallbackQuery.CONSTRUCTOR:
        return UpdateNewCallbackQuery.fromJson(json);
      case UpdateNewInlineCallbackQuery.CONSTRUCTOR:
        return UpdateNewInlineCallbackQuery.fromJson(json);
      case UpdateNewShippingQuery.CONSTRUCTOR:
        return UpdateNewShippingQuery.fromJson(json);
      case UpdateNewPreCheckoutQuery.CONSTRUCTOR:
        return UpdateNewPreCheckoutQuery.fromJson(json);
      case UpdateNewCustomEvent.CONSTRUCTOR:
        return UpdateNewCustomEvent.fromJson(json);
      case UpdateNewCustomQuery.CONSTRUCTOR:
        return UpdateNewCustomQuery.fromJson(json);
      case UpdatePoll.CONSTRUCTOR:
        return UpdatePoll.fromJson(json);
      case UpdatePollAnswer.CONSTRUCTOR:
        return UpdatePollAnswer.fromJson(json);
      case UpdateChatMember.CONSTRUCTOR:
        return UpdateChatMember.fromJson(json);
      case UpdateNewChatJoinRequest.CONSTRUCTOR:
        return UpdateNewChatJoinRequest.fromJson(json);
      default:
        return null;
    }
  }

  @override
  String getConstructor() => CONSTRUCTOR;
}
